# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: mashape-analytics 1.0.5 ruby lib

Gem::Specification.new do |s|
  s.name = "mashape-analytics"
  s.version = "1.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Kenneth Lee"]
  s.date = "2015-09-18"
  s.description = "The ruby agent reports API traffic to http://apianalytics.com"
  s.email = "kennethkl@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    ".editorconfig",
    ".travis.yml",
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/mashape-analytics.rb",
    "lib/mashape-analytics/capture.rb",
    "lib/mashape-analytics/frameworks.rb",
    "lib/mashape-analytics/frameworks/rack.rb",
    "lib/mashape-analytics/frameworks/rails.rb",
    "lib/mashape-analytics/frameworks/sinatra.rb",
    "lib/mashape-analytics/message.rb",
    "lib/mashape-analytics/message/alf.rb",
    "lib/mashape-analytics/utils.rb",
    "mashape-analytics.gemspec",
    "test/helper.rb",
    "test/test_capture.rb",
    "test/test_rack.rb",
    "test/test_sinatra.rb"
  ]
  s.homepage = "http://github.com/Mashape/analytics-agent-ruby"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "Ruby agent for Mashape Analytics"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rbczmq>, [">= 1.7.8", "~> 1.7"])
      s.add_development_dependency(%q<minitest>, ["~> 5.5"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<rails>, ["~> 4.1"])
      s.add_development_dependency(%q<sinatra>, ["~> 1.4"])
    else
      s.add_dependency(%q<rbczmq>, [">= 1.7.8", "~> 1.7"])
      s.add_dependency(%q<minitest>, ["~> 5.5"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<rails>, ["~> 4.1"])
      s.add_dependency(%q<sinatra>, ["~> 1.4"])
    end
  else
    s.add_dependency(%q<rbczmq>, [">= 1.7.8", "~> 1.7"])
    s.add_dependency(%q<minitest>, ["~> 5.5"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<rails>, ["~> 4.1"])
    s.add_dependency(%q<sinatra>, ["~> 1.4"])
  end
end

